name: All Saints Hackathon 2025
description: Submit a hackathon project.
title: "[Project]: project_title_here"
labels: ["hackathon-project"]
assignees:
  - RandyDanielson
body:
  - type: markdown
    attributes:
      value: |
        Welcome to the CatholicOS All Saints Hackathon 2025!
  - type: textarea
    id: project-team
    attributes:
      label: Project Team
      description: List the team members involved in this project (by github username) and possibly a team name.
      render: markdown
      placeholder: |
        Team: Carlo Acutis fellows (Assisi)
        - @username1
        - @username2
        - @username3
    validations:
      required: true
  - type: input
    id: project-slug
    attributes:
      label: Project Slug
      description: A short, URL-friendly identifier for your project (e.g., "awesome-ai-tool").
      placeholder: "awesome-ai-tool"
    validations:
      required: false
  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Please provide a brief description of your hackathon project.
      render: markdown
      placeholder: "A mobile-friendly web app that helps students navigate the campus, find available study spaces, and track campus events in real-time."
    validations:
      required: true
  - type: textarea
    id: project-technologies
    attributes:
      label: Technologies Used
      description: List the main technologies, frameworks, or tools used in this project.
      render: markdown
      placeholder: |
        - React Native
        - Node.js
        - MongoDB
    validations:
      required: false
